language: ruby
rvm:
  - 2.2
before_script:
  - wget https://codeload.github.com/dkhamsing/awesome_bot/tar.gz/ssl -O /tmp/temp.tar.gz
  - tar -xvf /tmp/temp.tar.gz
  - cd awesome_bot-ssl
  - bundle install
script:
  - ./bin/awesome_bot  
